Repository AchoBeta/achobeta-polaris, pull requests merged in 2024-11, with the labels that each got.

#12 feat: 更改流水线配置，优化 docker tag
  .github/pull-request-template.md
  .github/release-drafter.yml
  .github/workflows/pr-build-project.yml
  build.sh
  docs/dev-ops/docker-compose-app.yml
  polaris-app/build.sh
  tag-polaris.sh
Labels: 📒 Documentation, ✏️ Feature

#13 feat: 更改流水线配置，优化 docker tag
  .github/workflows/pr-build-project.yml
Labels: 📒 Documentation, ✏️ Feature

#14 feat: 更改流水线配置，优化 docker tag
  .github/workflows/pr-build-project.yml
Labels: ✏️ Feature

#16 feat: 更改流水线配置，优化 docker tag
  .github/pull-request-template.md
  .github/release-drafter.yml
  .github/workflows/pr-build-project.yml
  build.sh
  docs/dev-ops/app/start.sh
  docs/dev-ops/docker-compose-app.yml
  polaris-app/build.sh
  polaris-app/src/main/resources/application-dev.yml
  polaris-app/src/main/resources/application-prod.yml
  polaris-app/src/main/resources/application-test.yml
  polaris-trigger/src/main/java/com/achobeta/trigger/http/ReadController.java
  tag-polaris.sh
Labels: 📒 Documentation, ✏️ Feature

#17 feat: 更改流水线配置，优化 docker tag
  .github/workflows/pr-build-project.yml
  polaris-app/build.sh
  tag-polaris.sh
Labels: ✏️ Feature

#18 feat: 更改流水线配置，优化 docker tag
  .github/workflows/pr-build-project.yml
Labels: ✏️ Feature

#19 feat: 增强 PostContext 功能
  polaris-api/src/main/java/com/achobeta/api/dto/ReadRequestDTO.java
  polaris-api/src/main/java/com/achobeta/api/dto/RenderRequestDTO.java
  polaris-api/src/main/java/com/achobeta/api/dto/RenderResponseDTO.java
  polaris-domain/src/main/java/com/achobeta/domain/render/service/render/DefaultRenderTextService.java
  polaris-types/src/main/java/com/achobeta/types/common/BaseRequestParam.java
  polaris-types/src/main/java/com/achobeta/types/common/Constants.java
  polaris-types/src/main/java/com/achobeta/types/support/postprocessor/PostContext.java
Labels: ✏️ Feature

#51 feat: 扩展 PostProcessor 模板方法
  .github/workflows/pr-build-status.yml
  polaris-domain/src/main/java/com/achobeta/domain/render/service/render/FunctionRenderTextService.java
  polaris-trigger/src/main/java/com/achobeta/trigger/http/ReadController.java
  polaris-types/src/main/java/com/achobeta/types/support/postprocessor/AbstractFunctionPostProcessor.java
Labels: ✏️ Feature

#23 feat: 新建获取验证码接口
  .github/pull-request-template.md
  .github/workflows/pr-build-project.yml
  build.sh
  docs/dev-ops/docker-compose-app.yml
  polaris-api/src/main/java/com/achobeta/api/IGetCodeService.java
  polaris-api/src/main/java/com/achobeta/api/dto/GetCodeRequestDTO.java
  polaris-api/src/main/java/com/achobeta/api/dto/GetCodeResponseDTO.java
  polaris-app/build.sh
  polaris-domain/src/main/java/com/achobeta/domain/login/adapter/port/IShortMessageService.java
  polaris-domain/src/main/java/com/achobeta/domain/login/adapter/repository/IOperateCodeRepository.java
  polaris-domain/src/main/java/com/achobeta/domain/login/model/bo/SendCodeBO.java
  polaris-domain/src/main/java/com/achobeta/domain/login/model/entity/PhoneEntity.java
  polaris-domain/src/main/java/com/achobeta/domain/login/model/valobj/CodeVO.java
  polaris-domain/src/main/java/com/achobeta/domain/login/service/ISendCodeService.java
  polaris-domain/src/main/java/com/achobeta/domain/login/service/getcode/DefalutSendCodeService.java
  polaris-domain/src/main/java/com/achobeta/domain/login/service/getcode/SendCodePostProcessor.java
  polaris-domain/src/main/java/com/achobeta/domain/login/service/getcode/extendbiz/OperateCodePostProcessor.java
  polaris-infrastructure/src/main/java/com/achobeta/infrastructure/adapter/port/ShortMessageServicePort.java
  polaris-infrastructure/src/main/java/com/achobeta/infrastructure/adapter/repository/OperateCodeRepository.java
  polaris-trigger/src/main/java/com/achobeta/trigger/http/GetCodeController.java
  polaris-trigger/src/main/java/com/achobeta/trigger/http/ReadController.java
  polaris-types/pom.xml
  polaris-types/src/main/java/com/achobeta/types/enums/BizModule.java
  polaris-types/src/main/java/com/achobeta/types/enums/GlobalServiceStatusCode.java
  polaris-types/src/main/java/com/achobeta/types/enums/RedisKey.java
  tag-polaris.sh
Labels: 📒 Documentation, ✏️ Feature

#45 feat: 设备渲染模块
  polaris-api/src/main/java/com/achobeta/api/IDeviceService.java
  polaris-api/src/main/java/com/achobeta/api/dto/device/GetUserDeviceRequestDTO.java
  polaris-api/src/main/java/com/achobeta/api/dto/device/GetUserDeviceResponseDTO.java
  polaris-app/src/main/resources/mybatis/mapper/DeviceMapper.xml
  polaris-domain/src/main/java/com/achobeta/domain/device/adapter/repository/IDeviceRepository.java
  polaris-domain/src/main/java/com/achobeta/domain/device/model/bo/DeviceBO.java
  polaris-domain/src/main/java/com/achobeta/domain/device/model/entity/DeviceEntity.java
  polaris-domain/src/main/java/com/achobeta/domain/device/model/entity/PageResult.java
  polaris-domain/src/main/java/com/achobeta/domain/device/model/entity/UserCommonDevicesEntities.java
  polaris-domain/src/main/java/com/achobeta/domain/device/model/valobj/UserCommonDevicesVO.java
  polaris-domain/src/main/java/com/achobeta/domain/device/service/IDeviceService.java
  polaris-domain/src/main/java/com/achobeta/domain/device/service/get/DefaultDeviceService.java
  polaris-domain/src/main/java/com/achobeta/domain/device/service/get/DevicePostProcessor.java
  polaris-infrastructure/src/main/java/com/achobeta/infrastructure/adapter/repository/DeviceRepository.java
  polaris-infrastructure/src/main/java/com/achobeta/infrastructure/dao/DeviceMapper.java
  polaris-infrastructure/src/main/java/com/achobeta/infrastructure/dao/po/DevicePO.java
  polaris-trigger/src/main/java/com/achobeta/trigger/http/DeviceController.java
  polaris-types/src/main/java/com/achobeta/types/common/Constants.java
  polaris-types/src/main/java/com/achobeta/types/enums/BizModule.java
Labels: ✏️ Feature

#48 feat: 个人信息修改功能
  polaris-api/src/main/java/com/achobeta/api/IUserService.java
  polaris-api/src/main/java/com/achobeta/api/dto/user/ModifyUserInfoRequestDTO.java
  polaris-api/src/main/java/com/achobeta/api/dto/user/ModifyUserInfoResponseDTO.java
  polaris-app/src/main/resources/mybatis/mapper/UserMapper.xml
  polaris-domain/src/main/java/com/achobeta/domain/user/adapter/repository/IUserRepository.java
  polaris-domain/src/main/java/com/achobeta/domain/user/model/entity/UserEntity.java
  polaris-domain/src/main/java/com/achobeta/domain/user/service/IModifyUserInfoService.java
  polaris-domain/src/main/java/com/achobeta/domain/user/service/info/DefaultModifyUserInfoService.java
  polaris-domain/src/main/java/com/achobeta/domain/user/service/info/ModifyUserInfoPostProcessor.java
  polaris-infrastructure/src/main/java/com/achobeta/infrastructure/adapter/repository/UserRepository.java
  polaris-infrastructure/src/main/java/com/achobeta/infrastructure/dao/UserMapper.java
  polaris-infrastructure/src/main/java/com/achobeta/infrastructure/dao/po/UserPO.java
  polaris-trigger/src/main/java/com/achobeta/trigger/http/UserController.java
  polaris-types/src/main/java/com/achobeta/types/common/RedisKey.java
  polaris-types/src/main/java/com/achobeta/types/enums/BizModule.java
Labels: ✏️ Feature

#49 feat: 查看团队组织架构
  polaris-api/src/main/java/com/achobeta/api/ITeamService.java
  polaris-api/src/main/java/com/achobeta/api/dto/QueryStructureRequestDTO.java
  polaris-api/src/main/java/com/achobeta/api/dto/QueryStructureResponseDTO.java
  polaris-app/src/main/resources/mybatis/mapper/PositionMapper.xml
  polaris-domain/src/main/java/com/achobeta/domain/team/adapter/package-info.java
  polaris-domain/src/main/java/com/achobeta/domain/team/adapter/port/package-info.java
  polaris-domain/src/main/java/com/achobeta/domain/team/adapter/repository/IPositionRepository.java
  polaris-domain/src/main/java/com/achobeta/domain/team/adapter/repository/package-info.java
  polaris-domain/src/main/java/com/achobeta/domain/team/model/aggregate/package-info.java
  polaris-domain/src/main/java/com/achobeta/domain/team/model/bo/TeamBO.java
  polaris-domain/src/main/java/com/achobeta/domain/team/model/entity/PositionEntity.java
  polaris-domain/src/main/java/com/achobeta/domain/team/model/entity/package-info.java
  polaris-domain/src/main/java/com/achobeta/domain/team/model/valobj/package-info.java
  polaris-domain/src/main/java/com/achobeta/domain/team/service/IStructureService.java
  polaris-domain/src/main/java/com/achobeta/domain/team/service/package-info.java
  polaris-domain/src/main/java/com/achobeta/domain/team/service/structure/DefaultStructureService.java
  polaris-domain/src/main/java/com/achobeta/domain/team/service/structure/ViewStructurePostProcessor.java
  polaris-infrastructure/src/main/java/com/achobeta/infrastructure/adapter/repository/PositionRepository.java
  polaris-infrastructure/src/main/java/com/achobeta/infrastructure/dao/PositionMapper.java
  polaris-infrastructure/src/main/java/com/achobeta/infrastructure/redis/IRedisService.java
  polaris-infrastructure/src/main/java/com/achobeta/infrastructure/redis/RedissonService.java
  polaris-trigger/src/main/java/com/achobeta/trigger/http/TeamController.java
  polaris-types/src/main/java/com/achobeta/types/common/RedisKey.java
  polaris-types/src/main/java/com/achobeta/types/enums/BizModule.java
  polaris-types/src/main/java/com/achobeta/types/enums/GlobalServiceStatusCode.java
Labels: ✏️ Feature

#57 feat: 查看团队成员列表
  polaris-api/src/main/java/com/achobeta/api/ITeamService.java
  polaris-api/src/main/java/com/achobeta/api/dto/team/RequestMemberListDTO.java
  polaris-api/src/main/java/com/achobeta/api/dto/team/ResponseMemberListDTO.java
  polaris-app/src/main/resources/mybatis/mapper/UserMapper.xml
  polaris-domain/src/main/java/com/achobeta/domain/team/adapter/repository/IMemberRepository.java
  polaris-domain/src/main/java/com/achobeta/domain/team/model/bo/TeamBO.java
  polaris-domain/src/main/java/com/achobeta/domain/team/service/IMemberService.java
  polaris-domain/src/main/java/com/achobeta/domain/team/service/member/DefaultMemberService.java
  polaris-domain/src/main/java/com/achobeta/domain/team/service/member/MemberListPostProcessor.java
  polaris-domain/src/main/java/com/achobeta/domain/team/service/member/MemberPostProcessor.java
  polaris-domain/src/main/java/com/achobeta/domain/user/model/entity/UserEntity.java
  polaris-infrastructure/src/main/java/com/achobeta/infrastructure/adapter/repository/MemberRepository.java
  polaris-infrastructure/src/main/java/com/achobeta/infrastructure/adapter/repository/PositionRepository.java
  polaris-infrastructure/src/main/java/com/achobeta/infrastructure/dao/UserMapper.java
  polaris-trigger/src/main/java/com/achobeta/trigger/http/TeamController.java
  polaris-trigger/src/main/java/com/achobeta/trigger/http/UserController.java
  polaris-types/src/main/java/com/achobeta/types/common/Constants.java
Labels: ✏️ Feature

#61 feat: 查看团队成员信息详情
  polaris-api/src/main/java/com/achobeta/api/ITeamService.java
  polaris-api/src/main/java/com/achobeta/api/dto/QueryMemberInfoRequestDTO.java
  polaris-api/src/main/java/com/achobeta/api/dto/QueryMemberInfoResponseDTO.java
  polaris-app/src/main/resources/mybatis/mapper/PositionMapper.xml
  polaris-domain/src/main/java/com/achobeta/domain/team/adapter/repository/IMemberRepository.java
  polaris-domain/src/main/java/com/achobeta/domain/team/adapter/repository/IPositionRepository.java
  polaris-domain/src/main/java/com/achobeta/domain/team/model/bo/TeamBO.java
  polaris-domain/src/main/java/com/achobeta/domain/team/service/IMemberService.java
  polaris-domain/src/main/java/com/achobeta/domain/team/service/member/AddMemberPostProcessor.java
  polaris-domain/src/main/java/com/achobeta/domain/team/service/member/DefaultMemberService.java
  polaris-infrastructure/src/main/java/com/achobeta/infrastructure/adapter/repository/MemberRepository.java
  polaris-infrastructure/src/main/java/com/achobeta/infrastructure/adapter/repository/PositionRepository.java
  polaris-infrastructure/src/main/java/com/achobeta/infrastructure/dao/UserMapper.java
  polaris-trigger/src/main/java/com/achobeta/trigger/http/TeamController.java
Labels: ✏️ Feature

#62 feat: 添加团队成员
  polaris-api/src/main/java/com/achobeta/api/ITeamService.java
  polaris-api/src/main/java/com/achobeta/api/dto/AddMemberRequestDTO.java
  polaris-api/src/main/java/com/achobeta/api/dto/AddMemberResponseDTO.java
  polaris-app/src/main/resources/mybatis/mapper/PositionMapper.xml
  polaris-app/src/main/resources/mybatis/mapper/UserMapper.xml
  polaris-domain/src/main/java/com/achobeta/domain/team/adapter/repository/IMemberRepository.java
  polaris-domain/src/main/java/com/achobeta/domain/team/model/bo/TeamBO.java
  polaris-domain/src/main/java/com/achobeta/domain/team/service/IMemberService.java
  polaris-domain/src/main/java/com/achobeta/domain/team/service/member/AddMemberPostProcessor.java
  polaris-domain/src/main/java/com/achobeta/domain/team/service/member/DefaultMemberService.java
  polaris-infrastructure/src/main/java/com/achobeta/infrastructure/adapter/port/TeamInfoPort.java
  polaris-infrastructure/src/main/java/com/achobeta/infrastructure/adapter/repository/MemberRepository.java
  polaris-infrastructure/src/main/java/com/achobeta/infrastructure/adapter/repository/PositionRepository.java
  polaris-infrastructure/src/main/java/com/achobeta/infrastructure/dao/PositionMapper.java
  polaris-infrastructure/src/main/java/com/achobeta/infrastructure/dao/UserMapper.java
  polaris-infrastructure/src/main/java/com/achobeta/infrastructure/dao/po/UserPO.java
  polaris-trigger/src/main/java/com/achobeta/trigger/http/TeamController.java
Labels: ✏️ Feature

#68 feat: 测试
  polaris-types/src/main/java/com/achobeta/types/support/util/PatternStrUtil.java
Labels: ✏️ Feature

#63 feat: 删除团队成员
  polaris-api/src/main/java/com/achobeta/api/ITeamService.java
  polaris-api/src/main/java/com/achobeta/api/dto/DeleteMemberRequestDTO.java
  polaris-api/src/main/java/com/achobeta/api/dto/DeleteMemberResponseDTO.java
  polaris-api/src/main/java/com/achobeta/api/dto/QueryMemberInfoResponseDTO.java
  polaris-api/src/main/java/com/achobeta/api/dto/user/QueryUserInfoResponseDTO.java
  polaris-app/src/main/resources/mybatis/mapper/UserMapper.xml
  polaris-domain/src/main/java/com/achobeta/domain/team/adapter/repository/IMemberRepository.java
  polaris-domain/src/main/java/com/achobeta/domain/team/service/IMemberService.java
  polaris-domain/src/main/java/com/achobeta/domain/team/service/member/DefaultMemberService.java
  polaris-domain/src/main/java/com/achobeta/domain/team/service/member/DeleteMemberPostProcessor.java
  polaris-infrastructure/src/main/java/com/achobeta/infrastructure/adapter/repository/MemberRepository.java
  polaris-infrastructure/src/main/java/com/achobeta/infrastructure/dao/UserMapper.java
  polaris-trigger/src/main/java/com/achobeta/trigger/http/TeamController.java
Labels: ✏️ Feature

#67 fix: 登录模块修改bug,简化代码
  polaris-api/src/main/java/com/achobeta/api/IGetCodeService.java
  polaris-api/src/main/java/com/achobeta/api/ILoginService.java
  polaris-api/src/main/java/com/achobeta/api/ILogoutService.java
  polaris-api/src/main/java/com/achobeta/api/dto/GetCodeRequestDTO.java
  polaris-api/src/main/java/com/achobeta/api/dto/LoginRequestDTO.java
  polaris-api/src/main/java/com/achobeta/api/dto/LoginResponseDTO.java
  polaris-app/src/main/java/com/achobeta/aop/LoginVerificationAspect.java
  polaris-app/src/main/resources/mybatis/mapper/DeviceMapper.xml
  polaris-domain/src/main/java/com/achobeta/domain/login/adapter/repository/IDeviceRepository.java
  polaris-domain/src/main/java/com/achobeta/domain/login/adapter/repository/ITokenRepository.java
  polaris-domain/src/main/java/com/achobeta/domain/login/model/entity/DeviceEntity.java
  polaris-domain/src/main/java/com/achobeta/domain/login/model/valobj/LoginVO.java
  polaris-domain/src/main/java/com/achobeta/domain/login/model/valobj/TokenVO.java
  polaris-domain/src/main/java/com/achobeta/domain/login/service/IAuthorizationService.java
  polaris-domain/src/main/java/com/achobeta/domain/login/service/login/DefalutLoginService.java
  polaris-domain/src/main/java/com/achobeta/domain/login/service/login/extendbiz/OperateDevicePostProcessor.java
  polaris-domain/src/main/java/com/achobeta/domain/login/service/refresh/DefaultRefreshTokenService.java
  polaris-infrastructure/src/main/java/com/achobeta/infrastructure/adapter/port/TeamInfoPort.java
  polaris-infrastructure/src/main/java/com/achobeta/infrastructure/adapter/repository/DeviceRepository.java
  polaris-infrastructure/src/main/java/com/achobeta/infrastructure/adapter/repository/OperateCodeRepository.java
  polaris-infrastructure/src/main/java/com/achobeta/infrastructure/adapter/repository/TokenRepository.java
  polaris-infrastructure/src/main/java/com/achobeta/infrastructure/dao/DeviceMapper.java
  polaris-infrastructure/src/main/java/com/achobeta/infrastructure/dao/po/DevicePO.java
  polaris-trigger/src/main/java/com/achobeta/trigger/http/GetCodeController.java
  polaris-trigger/src/main/java/com/achobeta/trigger/http/LoginController.java
  polaris-trigger/src/main/java/com/achobeta/trigger/http/LogoutController.java
  polaris-trigger/src/main/java/com/achobeta/trigger/http/ReadController.java
  polaris-types/src/main/java/com/achobeta/types/Response.java
  polaris-types/src/main/java/com/achobeta/types/common/RedisKey.java
  polaris-types/src/main/java/com/achobeta/types/enums/GlobalServiceStatusCode.java
  polaris-types/src/main/java/com/achobeta/types/enums/RedisKey.java
  polaris-types/src/main/java/com/achobeta/types/exception/GlobalExceptionHandler.java
  polaris-types/src/main/java/com/achobeta/types/support/util/TokenUtil.java
Labels: ☢️ Bug

#65 feat: 鉴权的实现demo
  polaris-api/src/main/java/com/achobeta/api/dto/AuthRequestDTO.java
  polaris-app/src/main/java/com/achobeta/aop/AuthVerifyAspect.java
  polaris-app/src/main/resources/mybatis/mapper/PermissionMapper.xml
  polaris-app/src/main/resources/mybatis/mapper/RoleMapper.xml
  polaris-domain/src/main/java/com/achobeta/domain/auth/adapter/repository/IAuthRepository.java
  polaris-domain/src/main/java/com/achobeta/domain/auth/model/bo/AuthBO.java
  polaris-domain/src/main/java/com/achobeta/domain/auth/model/entity/PermissionEntity.java
  polaris-domain/src/main/java/com/achobeta/domain/auth/model/entity/RoleEntity.java
  polaris-domain/src/main/java/com/achobeta/domain/auth/service/IAuthVerifyService.java
  polaris-domain/src/main/java/com/achobeta/domain/auth/service/verify/IAuthVerifyPostProcessor.java
  polaris-infrastructure/src/main/java/com/achobeta/infrastructure/adapter/repository/AuthRepository.java
  polaris-infrastructure/src/main/java/com/achobeta/infrastructure/dao/PermissionMapper.java
  polaris-infrastructure/src/main/java/com/achobeta/infrastructure/dao/RoleMapper.java
  polaris-infrastructure/src/main/java/com/achobeta/infrastructure/dao/po/PermissionPO.java
  polaris-infrastructure/src/main/java/com/achobeta/infrastructure/dao/po/RolePO.java
  polaris-trigger/src/main/java/com/achobeta/trigger/http/AuthController.java
  polaris-trigger/src/main/java/com/achobeta/trigger/http/TeamController.java
  polaris-types/src/main/java/com/achobeta/types/annotation/AuthVerify.java
  polaris-types/src/main/java/com/achobeta/types/common/RedisKey.java
Labels: ✏️ Feature

#54 feat: 公告渲染页面
  polaris-api/src/main/java/com/achobeta/api/IAnnounceService.java
  polaris-api/src/main/java/com/achobeta/api/dto/announce/GetUserAnnounceCountRequestDTO.java
  polaris-api/src/main/java/com/achobeta/api/dto/announce/GetUserAnnounceCountResponseDTO.java
  polaris-api/src/main/java/com/achobeta/api/dto/announce/GetUserAnnounceRequestDTO.java
  polaris-api/src/main/java/com/achobeta/api/dto/announce/GetUserAnnounceResponseDTO.java
  polaris-api/src/main/java/com/achobeta/api/dto/announce/ReadAllAnnounceRequestDTO.java
  polaris-api/src/main/java/com/achobeta/api/dto/announce/ReadAnnounceRequestDTO.java
  polaris-app/src/main/resources/mybatis/mapper/AnnounceMapper.xml
  polaris-domain/src/main/java/com/achobeta/domain/announce/adapter/repository/IAnnounceRepository.java
  polaris-domain/src/main/java/com/achobeta/domain/announce/model/bo/AnnounceBO.java
  polaris-domain/src/main/java/com/achobeta/domain/announce/model/entity/AnnounceCountEntity.java
  polaris-domain/src/main/java/com/achobeta/domain/announce/model/entity/AnnounceEntity.java
  polaris-domain/src/main/java/com/achobeta/domain/announce/model/entity/PageResult.java
  polaris-domain/src/main/java/com/achobeta/domain/announce/model/entity/ReadAnnounceEntity.java
  polaris-domain/src/main/java/com/achobeta/domain/announce/model/entity/UserAnnounceEntity.java
  polaris-domain/src/main/java/com/achobeta/domain/announce/model/valobj/UserAnnounceVO.java
  polaris-domain/src/main/java/com/achobeta/domain/announce/service/DefaultAnnounceService.java
  polaris-domain/src/main/java/com/achobeta/domain/announce/service/IAnnounceService.java
  polaris-domain/src/main/java/com/achobeta/domain/announce/service/get/AnnounceCountPostProcessor.java
  polaris-domain/src/main/java/com/achobeta/domain/announce/service/get/AnnouncePostProcessor.java
  polaris-domain/src/main/java/com/achobeta/domain/announce/service/read/ReadAllAnnouncePostProcessor.java
  polaris-domain/src/main/java/com/achobeta/domain/announce/service/read/ReadAnnouncePostProcessor.java
  polaris-domain/src/main/java/com/achobeta/domain/device/service/get/DefaultDeviceService.java
  polaris-infrastructure/src/main/java/com/achobeta/infrastructure/adapter/repository/AnnounceRepository.java
  polaris-infrastructure/src/main/java/com/achobeta/infrastructure/dao/AnnounceMapper.java
  polaris-infrastructure/src/main/java/com/achobeta/infrastructure/dao/po/AnnouncePO.java
  polaris-infrastructure/src/main/java/com/achobeta/infrastructure/dao/po/AnnounceReciverPO.java
  polaris-trigger/src/main/java/com/achobeta/trigger/http/AnnounceController.java
  polaris-trigger/src/main/java/com/achobeta/trigger/http/DeviceController.java
  polaris-types/src/main/java/com/achobeta/types/common/Constants.java
  polaris-types/src/main/java/com/achobeta/types/enums/BizModule.java
Labels: ✏️ Feature

#72 Revert "feat: 新增访问私有资源拦截注解,给需要的接口添加登陆校验注解"
  polaris-api/src/main/java/com/achobeta/api/dto/like/LikeRequestDTO.java
  polaris-app/src/main/java/com/achobeta/aop/AuthVerifyAspect.java
  polaris-app/src/main/java/com/achobeta/aop/LoginVerificationAspect.java
  polaris-app/src/main/java/com/achobeta/aop/SelfPermissionVerificationAspect.java
  polaris-trigger/src/main/java/com/achobeta/trigger/http/AnnounceController.java
  polaris-trigger/src/main/java/com/achobeta/trigger/http/AuthController.java
  polaris-trigger/src/main/java/com/achobeta/trigger/http/DeviceController.java
  polaris-trigger/src/main/java/com/achobeta/trigger/http/LikeController.java
  polaris-trigger/src/main/java/com/achobeta/trigger/http/ReadController.java
  polaris-trigger/src/main/java/com/achobeta/trigger/http/TeamController.java
  polaris-trigger/src/main/java/com/achobeta/trigger/http/UserController.java
  polaris-types/src/main/java/com/achobeta/types/constraint/LoginVerification.java
  polaris-types/src/main/java/com/achobeta/types/constraint/SelfPermissionVerification.java
Labels: Invalid PR Title, ✏️ Feature

#73 feat: 调整点赞状态，补充到个人信息和成员信息中
  polaris-app/src/main/resources/mybatis/mapper/LikeMapper.xml
  polaris-domain/src/main/java/com/achobeta/domain/team/adapter/repository/IMemberRepository.java
  polaris-domain/src/main/java/com/achobeta/domain/team/service/IMemberService.java
  polaris-domain/src/main/java/com/achobeta/domain/team/service/member/DefaultMemberService.java
  polaris-infrastructure/src/main/java/com/achobeta/infrastructure/adapter/repository/LikeRepository.java
  polaris-infrastructure/src/main/java/com/achobeta/infrastructure/adapter/repository/MemberRepository.java
  polaris-infrastructure/src/main/java/com/achobeta/infrastructure/adapter/repository/UserRepository.java
  polaris-infrastructure/src/main/java/com/achobeta/infrastructure/dao/LikeMapper.java
  polaris-trigger/src/main/java/com/achobeta/trigger/http/TeamController.java
Labels: ✏️ Feature

#76 feat: 修正成员权限部分逻辑，修复无数bug
  docs/dev-ops/mysql/sql/device.sql
  docs/dev-ops/mysql/sql/member.sql
  docs/dev-ops/mysql/sql/position.sql
  docs/dev-ops/mysql/sql/rbac_role_permission.sql
  docs/dev-ops/mysql/sql/user.sql
  polaris-api/src/main/java/com/achobeta/api/dto/AddMemberRequestDTO.java
  polaris-api/src/main/java/com/achobeta/api/dto/ListRoleRequestDTO.java
  polaris-api/src/main/java/com/achobeta/api/dto/ListRoleResponseDTO.java
  polaris-api/src/main/java/com/achobeta/api/dto/LoginResponseDTO.java
  polaris-api/src/main/java/com/achobeta/api/dto/ModifyMemberInfoRequestDTO.java
  polaris-api/src/main/java/com/achobeta/api/dto/QueryMemberInfoResponseDTO.java
  polaris-api/src/main/java/com/achobeta/api/dto/user/QueryUserInfoResponseDTO.java
  polaris-app/src/main/java/com/achobeta/aop/AuthVerifyAspect.java
  polaris-app/src/main/resources/mybatis/mapper/PositionMapper.xml
  polaris-app/src/main/resources/mybatis/mapper/RoleMapper.xml
  polaris-app/src/main/resources/mybatis/mapper/UserMapper.xml
  polaris-domain/src/main/java/com/achobeta/domain/auth/adapter/repository/IAuthRepository.java
  polaris-domain/src/main/java/com/achobeta/domain/auth/model/bo/AuthBO.java
  polaris-domain/src/main/java/com/achobeta/domain/auth/model/entity/PermissionEntity.java
  polaris-domain/src/main/java/com/achobeta/domain/auth/model/entity/RoleEntity.java
  polaris-domain/src/main/java/com/achobeta/domain/auth/service/IRoleService.java
  polaris-domain/src/main/java/com/achobeta/domain/auth/service/role/DefaultRoleService.java
  polaris-domain/src/main/java/com/achobeta/domain/auth/service/role/QueryRolesPostProcessor.java
  polaris-domain/src/main/java/com/achobeta/domain/auth/service/role/RolePostProcessor.java
  polaris-domain/src/main/java/com/achobeta/domain/login/adapter/port/ITeamInfoPort.java
  polaris-domain/src/main/java/com/achobeta/domain/login/model/bo/LoginBO.java
  polaris-domain/src/main/java/com/achobeta/domain/login/model/valobj/LoginVO.java
  polaris-domain/src/main/java/com/achobeta/domain/login/service/login/DefalutLoginService.java
  polaris-domain/src/main/java/com/achobeta/domain/login/service/refresh/DefaultRefreshTokenService.java
  polaris-domain/src/main/java/com/achobeta/domain/team/adapter/repository/IMemberRepository.java
  polaris-domain/src/main/java/com/achobeta/domain/team/adapter/repository/IPositionRepository.java
  polaris-domain/src/main/java/com/achobeta/domain/team/model/entity/PositionEntity.java
  polaris-domain/src/main/java/com/achobeta/domain/team/model/entity/TeamEntity.java
  polaris-domain/src/main/java/com/achobeta/domain/team/service/IMemberService.java
  polaris-domain/src/main/java/com/achobeta/domain/team/service/member/DefaultMemberService.java
  polaris-domain/src/main/java/com/achobeta/domain/team/service/structure/DefaultStructureService.java
  polaris-domain/src/main/java/com/achobeta/domain/user/model/entity/UserEntity.java
  polaris-infrastructure/src/main/java/com/achobeta/infrastructure/adapter/port/TeamInfoPort.java
  polaris-infrastructure/src/main/java/com/achobeta/infrastructure/adapter/repository/AnnounceRepository.java
  polaris-infrastructure/src/main/java/com/achobeta/infrastructure/adapter/repository/AuthRepository.java
  polaris-infrastructure/src/main/java/com/achobeta/infrastructure/adapter/repository/MemberRepository.java
  polaris-infrastructure/src/main/java/com/achobeta/infrastructure/adapter/repository/PositionRepository.java
  polaris-infrastructure/src/main/java/com/achobeta/infrastructure/adapter/repository/UserRepository.java
  polaris-infrastructure/src/main/java/com/achobeta/infrastructure/dao/PermissionMapper.java
  polaris-infrastructure/src/main/java/com/achobeta/infrastructure/dao/PositionMapper.java
  polaris-infrastructure/src/main/java/com/achobeta/infrastructure/dao/RoleMapper.java
  polaris-infrastructure/src/main/java/com/achobeta/infrastructure/dao/UserMapper.java
  polaris-infrastructure/src/main/java/com/achobeta/infrastructure/dao/po/UserPO.java
  polaris-trigger/src/main/java/com/achobeta/trigger/http/AnnounceController.java
  polaris-trigger/src/main/java/com/achobeta/trigger/http/AuthController.java
  polaris-trigger/src/main/java/com/achobeta/trigger/http/DeviceController.java
  polaris-trigger/src/main/java/com/achobeta/trigger/http/LikeController.java
  polaris-trigger/src/main/java/com/achobeta/trigger/http/LoginController.java
  polaris-trigger/src/main/java/com/achobeta/trigger/http/TeamController.java
  polaris-trigger/src/main/java/com/achobeta/trigger/http/UserController.java
  polaris-types/src/main/java/com/achobeta/types/common/RedisKey.java
  polaris-types/src/main/java/com/achobeta/types/enums/GlobalServiceStatusCode.java
  polaris-types/src/main/java/com/achobeta/types/support/util/buildKeyUtil.java
Labels: ✏️ Feature, ☢️ Bug
